name: GCloud Dev - ETH Nicehash


# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ master ] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NAMESPACE: dev-dizim
  APP_NAME: e-test-nicehash

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup-build-publish-deploy:
    name: Build and push docker image to Google Artifact Registry
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@master

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GOOGLE_PROVIDER_ID }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}@${{ secrets.GOOGLE_PROJECT_ID }}.iam.gserviceaccount.com
          access_token_lifetime: 3600s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: asia-southeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # Container build and push to a Azure Container Registry (ACR)
      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: |
            asia-southeast1-docker.pkg.dev/api-project-608799452172/dev-dizim-registry/e-test-nicehash:${{ github.sha }}
            asia-southeast1-docker.pkg.dev/api-project-608799452172/dev-dizim-registry/e-test-nicehash:latest